version: "3"
services:
  db:
    container_name: db
    image: mongo:4.0
    restart: always
    ports:
      - '27017:27017'
  qawolf:
    container_name: qawolf
    image: qabuild:latest
    restart: always
    environment:
      - QAW_HEADLESS=true
