- name: Deploy Simple Todo app on EC2 instance
  hosts: all

  tasks: 
    # - name: Create a file called '/tmp/testfile.txt' with the content 'hello world'.
    #   copy:
    #     content: hello worldn
    #     dest: /tmp/testfile.txt
    - name: Extract simpletodoapp-#.#.#.tgz into /etc/
      unarchive:
        src: /files/simpletodoapp-1.0.1.tgz
        dest: /etc/simpletodoapp-1.0.1
        remote_src: yes