- name: Deploy Simple Todo app on EC2 instance
  hosts: all
  vars:
    db_endpoint: ""
    db_username: ""
    db_password: ""
    db_port: ""

  tasks:
    - name: Create app/dist directory in /etc if it does not exist
      become: yes
      file:
        path: /etc/app/dist
        state: directory

    - name: Extract simpletodoapp-#.#.#.tgz into /etc/app/dist
      become: yes
      unarchive:
        src: "files/simpletodoapp-1.0.1.tgz"
        dest: /etc/app/dist

    - name: Updating system and installing dependencies
      become: yes
      shell: |
        sudo yum update -y
        sudo yum upgrade -y
        sudo yum install gcc-c++ make -y
        curl -fsSL https://rpm.nodesource.com/setup_lts.x | bash -
        sudo yum install -y nodejs

    - name: Installing Node dependencies
      become: yes
      shell: |
        cd /etc/app/dist/package
        sudo npm install

    - name: Create the service file from the template
      become: yes
      template:
        src: templates/service.tpl
        dest: /usr/lib/systemd/system/simpletodoapp.service

    - name: Start and enable the simpletodoapp service
      become: yes
      service:
        name: simpletodoapp
        state: enabled
        enable: yes