- name: Deploy Simple Todo app on EC2 instance
  hosts: all

  tasks: 
    - name: Create simpletodoapp directory in /etc if it does not exist
      file:
        path: /etc/simpletodoapp
        state: directory
        mode: '0755'
      become: yes
      
    - name: Extract simpletodoapp-#.#.#.tgz into /etc/simpletodoapp
      unarchive:
        src: files/simpletodoapp-1.0.1.tgz
        dest: /etc/simpletodoapp
      become: yes
       