- name: Deploy Simple Todo app on EC2 instance
  hosts: all
  vars:
    dir_name: "simpletodoapp-1.0.1"
    db_endpoint: ""
    db_user: ""
    db_password: ""
    db_port: ""

  tasks:
    - name: Create simpletodoapp directory in /etc if it does not exist
      become: yes
      file:
        path: /etc/simpletodoapp
        state: directory

    - name: Extract simpletodoapp-#.#.#.tgz into /etc/simpletodoapp
      become: yes
      unarchive:
        src: "files/{{ dir_name }}.tgz"
        dest: /etc/simpletodoapp

    - name: Updating system and installing dependencies
      become: yes
      shell: |
        sudo yum update -y
        sudo yum upgrade -y
        sudo yum install gcc-c++ make -y
        curl -fsSL https://rpm.nodesource.com/setup_lts.x | bash -
        sudo yum install -y nodejs

    - name: Installing Node dependencies
      become: yes
      shell: |
        cd /etc/simpletodoapp/package/
        sudo npm install

    - name: ansible.builtin.template
    # do shit here